### ISSUE TITLE
Conditional compilation for TCKT

### ISSUE THREAD

**Issue by mnsaglam** [KimlikDAO/TCKT#3]
With TCKT deployment approaching, we need to figure out a conditional compilation tool.

TCKT contract is deployed at the same address across all EVM chains. The deployed bytecode is almost identical (save for chainId literal), except in Avalanche C-chain, where it has additional mappings.

 - `exposureReported(address => timestamp)`
 - `publicKeys`

and the related methods for manipulating and reading this data. Whenever we have data that needs to be agreed upon together (through on-chain voting) but consumed off-chain, we keep it only on one chain--Avalanche C.

Figure out a conditional compilation tool, or hack our own tool so that we can take TCKT.sol and compile a bytecode for each supported chain.

**Comment by 0x471** [comment]
https://github.com/KimlikDAO/TCKT/pull/6
